# Generated by Django 3.0.8 on 2020-07-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('screenshot', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('time_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
