# Generated by Django 3.0.8 on 2020-07-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('screenshot', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('time_published', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubmittedForm',
        ),
    ]
